# Generated by Django 3.0.4 on 2020-04-02 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('info', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('location', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
    ]
