# Generated by Django 3.0.4 on 2020-04-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
